#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: name_tty ttyPort newName"
  exit 0
fi

USB_Ser=$(udevadm info -a -n $1 | grep '{serial}' | head -n1 )
LINE+="SUBSYSTEMS==\"usb\", KERNEL==\"ttyUSB[0-9]*\", ATTRS{idVendor}==\"0403\", ATTRS{idProduct}==\"6001\"," LINE+=$USB_Ser
LINE+=", SYMLINK+=\"$2\""

echo "Implementing new rule: $2"
echo $LINE >> /etc/udev/rules.d/90-usb-serial.rules

echo "Restarting udev"
restart udev	# make udev reload rules
