#!/bin/bash
# script to record various system characteristics

# System Time
FILENAME="/var/log/performance/"$(date +%Y%m%d)"_Monitor.csv"
TIME=$(date +%H:%M:%S)

if [ ! -e $FILENAME ]
then
  echo "Time, \"CPU 1 Min\",\" CPU 5 Min\",\"CPU 15 Min\",\"Total Mem\",\" Used Mem\",\" Free Mem\",\" Shared Mem\",\" Buffer Mem\",\" Cached Mem\",\"Eth KB/s In\",\"Eth KB/s Out\",\"Temperature\"" > $FILENAME
fi

#==============================================
# grab ethernet data
ETH=$(ifstat -n -i eth0 1 1 | grep -v KB |\
	 grep -v eth0 |\
	 sed -e 's/      /,/g')

#==============================================
# grab CPU
CPU_1=$(uptime | sed -e 's/.*load average: \(.*\...\), \(.*\...\), \(.*\...\)/\1/' -e 's/ //g')
CPU_5=$(uptime | sed -e 's/.*load average: \(.*\...\), \(.*\...\), \(.*\...\)/\2/' -e 's/ //g')
CPU_15=$(uptime | sed -e 's/.*load average: \(.*\...\), \(.*\...\), \(.*\...\)/\3/' -e 's/ //g')

#==============================================
# grab Memory
MEM=$(free -bm | grep Mem: |\
	 sed -e 's/Mem: *//' -e 's/ ?/,/g' \
	 -e 's/      /,/g')

#==============================================
# grab Temperature
#TEMP=$(sensors | grep temp | cut -d '+' -f 2 | cut -d 'C' -f 1  )
TEMP="N/A"

#==============================================
# record to a file
LINE=$TIME','$CPU_1','$CPU_5','$CPU_15','$MEM','$ETH','$TEMP

echo $LINE >> $FILENAME

#==========================
#==========================
