#!/bin/bash
# Log in and start Sub remotely.

# SSH details for the router and ROSV.
SUB="pi@192.168.4.200"
ROUTER="thomas@192.168.4.1"

ping -c 1 $ROUTER > /dev/null
ping -c 1 $SUB > /dev/null

echo "Start Console"
echo "Starting Submarine Console"
logger "Start ROSV"
logger "Now attempting to connect to ROSV"


# Check Video Receiver is running.
echo "Starting Listner"
nohup PC_Stream 0<&- & #&> /dev/null &
sleep 2

# Log into submarine and start ROSV_Control
echo "Start ROSV_Control"
ssh $SUB 'sudo ROSV_Control'

echo "Start Joystick program"
ssh $ROUTER 'pkill ROSV_Joystick'
ssh $ROUTER 'ROSV_Joystick'

# Start local system
echo "Start Camera"
./create_cam_link.py

echo "Start up complete"
