#!/bin/bash
install PC_Stream /usr/local/bin
install RPI_Cam_Start  /usr/local/bin
install RPI_Stop_Cam /usr/local/bin
install RPI_Stream /usr/local/bin
install start_ROSV /usr/local/bin
install set_time /usr/local/bin


