#!/bin/bash
# Options
res="160x120"
framerate="3"
quality="100"
cam_device="/dev/video0"

mjpg_streamer -i "/usr/lib/input_uvc.so -y -d $cam_device -r $res -f $framerate -q $quality -n" -o "/usr/lib/output_http.so -n"
echo "Script has shutdown"

